PROPRIETARY LICENSE

Copyright (c) 2025 МЕЛЬНИК ЄВГЕНІЙ СТАНІСЛАВОВИЧ [TELEGRAM:@ACABSTRACT]

All rights reserved.

This software is the confidential and proprietary information of МЕЛЬНИК ЄВГЕНІЙ СТАНІСЛАВОВИЧ.
You shall not disclose, copy, modify, or distribute this software without
the express written permission of the author.

This software is provided for use only by the licensed purchaser.
